name: Build and Test Client

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Add execution permissions to the Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew setupCIWorkspace build -Penv=${{ github.ref_name == 'master' && 'release' || 'debug' }} --no-daemon

      - name: Test
        run: ./gradlew test

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/libs/*.jar